In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("./train.csv", engine='python', encoding="utf-8")
df.head(20)

,Date,stations,observation,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014/1/1,station,AMB_TEMP,14,14,14,13,12,12,12,...,22,22,21,19,17,16,15,15,15,15
1,2014/1/1,station,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,2014/1/1,station,CO,0.51,0.41,0.39,0.37,0.35,0.3,0.37,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,2014/1/1,station,NMHC,0.2,0.15,0.13,0.12,0.11,0.06,0.1,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,2014/1/1,station,NO,0.9,0.6,0.5,1.7,1.8,1.5,1.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
5,2014/1/1,station,NO2,16,9.2,8.2,6.9,6.8,3.8,6.9,...,11,11,22,28,19,12,8.1,7,6.9,6
6,2014/1/1,station,NOx,17,9.8,8.7,8.6,8.5,5.3,8.8,...,14,13,25,30,21,13,9.7,8.6,8.7,7.5
7,2014/1/1,station,O3,16,30,27,23,24,28,24,...,65,64,51,34,33,34,37,38,38,36
8,2014/1/1,station,PM10,56,50,48,35,25,12,4,...,52,51,66,85,85,63,46,36,42,42
9,2014/1/1,station,PM2.5,26,39,36,35,31,28,25,...,36,45,42,49,45,44,41,30,24,13
10,2014/1/1,station,RAINFALL,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR
11,2014/1/1,station,RH,77,68,67,74,72,73,74,...,47,49,56,67,72,69,70,70,70,69
12,2014/1/1,station,SO2,1.8,2,1.7,1.6,1.9,1.4,1.5,...,3.9,4.4,9.9,5.1,3.4,2.3,2,1.9,1.9,1.9
13,2014/1/1,station,THC,2,2,2,1.9,1.9,1.8,1.9,...,1.9,1.9,1.9,2.1,2,1.9,1.9,1.9,1.9,1.9
14,2014/1/1,station,WD_HR,37,80,57,76,110,106,101,...,307,304,307,124,118,121,113,112,106,110
15,2014/1/1,station,WIND_DIREC,35,79,2.4,55,94,116,106,...,313,305,291,124,119,118,114,108,102,111
16,2014/1/1,station,WIND_SPEED,1.4,1.8,1,0.6,1.7,2.5,2.5,...,2.5,2.2,1.4,2.2,2.8,3,2.6,2.7,2.1,2.1
17,2014/1/1,station,WS_HR,0.5,0.9,0.6,0.3,0.6,1.9,2,...,2.1,2.1,1.9,1,2.5,2.5,2.8,2.6,2.4,2.3
18,2014/1/2,station,AMB_TEMP,16,15,15,14,14,15,16,...,24,24,23,21,20,19,18,18,18,18
19,2014/1/2,station,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8

In [3]:
df = df[df['observation']=='PM2.5']
df = df.drop(['Date', 'stations', 'observation'], axis=1)

In [4]:
X_train = []
y_train = []

for i in range(15):
    X = df.iloc[:,i:i+9]
    X_train.append(X)
    y_train.append(df.iloc[:,i+9])
X_train = np.array(X_train, dtype='float').reshape(3600,9)
y_train = np.array(y_train, dtype='float').reshape(3600)

In [5]:
from playML.LinearRegression import LinearRegression
from sklearn.preprocessing import StandardScaler

lin_reg = LinearRegression()
lin_reg.fit_gd(X_train, y_train,eta=0.0001)
lin_reg.coef_

0.02011028608074497

In [6]:
lin_reg.score(X_train, y_train)

0.8535116131805641

In [7]:
df_test = pd.read_csv("./test.csv", engine='python', encoding="utf-8", header=None)
df_test = df_test[df_test[1]=='PM2.5']
df_test.drop([0,1], axis=1, inplace=True)
df_test.head()

    2   3   4   5   6   7   8   9   10
9   27  13  24  29  41  30  29  27  28
27  46  47  57  78  84  76  59  61  61
45  10  10  25  34  40  39  36  25  22
63  71  58  51  41  41  46  43  34  29
81  13  23  18  10   5   5  13   9  12

In [8]:
df_result = pd.read_csv("./result.csv", engine='python', encoding="utf-8")
df_result.drop(['Unnamed: 0','id'], axis=1, inplace=True)
df_result.head()

       value
0  23.323052
1  50.826149
2  17.770002
3  24.896309
4   9.889757

In [9]:
X_test = np.array(df_test, dtype='float')
y_test = np.array(df_result, dtype='float')

In [10]:
lin_reg.predict(X_test)

array([ 27.3263542 ,  62.69504988,  20.19818306,  30.10811902,
        10.01382896,  36.13491956,  40.32094016,  16.04577251,
        49.36346016,  33.67139392,  39.31899572,  59.08543219,
        37.97429957,  41.83304163,  28.44886159,  12.65545708,
        52.89826715,  23.82907731,  19.26063444,  20.07012408,
        14.85397722,  28.21243036,  38.41494772,  11.44796304,
        58.97426892,  44.38903203,  28.44696125,   9.12921678,
        29.48074607,  36.01620205,  18.94094068,  11.96670717,
        16.5493243 ,   8.69653333,  18.71150025,  38.77504204,
        19.95370595,  28.19902808,   5.88481792,  59.79538435,
        46.58662984,  17.3570237 ,  50.18543187,  18.76339699,
        44.00084809,  51.9880979 ,  62.68625553,  40.75910993,
        51.21694853,  41.78063923,  31.14404549,  25.3599038 ,
        40.95537276,  26.27733642,  38.30070302,  40.07553323,
        25.72046011,  22.37335392,  37.49170452,  31.96217116,
        15.20965601,  23.27116879,  31.68871953,  55.63447904,
        50.38009307,  27.12069543,  42.27929574,  54.47910488,
        28.62577317,  40.16977959,  65.4063812 ,  54.16664778,
        45.21778672,  10.87988203,  12.88855756,  37.98888681,
        61.89792088,   2.88481858,  46.40353227,  41.65340379,
         8.14407831,  22.22519984,   7.22686789,  33.85256738,
        11.19688081,   4.84909676,  16.06175517,  11.40669017,
        12.96058188,  27.80321912,  30.09757942,  11.00335522,
        13.77300797,   7.55349044,  36.0718476 ,  15.76077051,
        15.67430082,   8.30081652,  10.82291424,   3.86193774,
        12.89076384,  18.02432509,  10.99830477,   5.17101453,
        14.23822915,  36.7574787 ,  27.13908775,   7.95371035,
        16.23972004,  16.294186  ,  14.15945167,  17.63411892,
        13.21948073,  28.06937964,  22.97724106,  14.85764203,
         9.58747174,  44.3940006 ,  30.72805914,   1.176476  ,
         1.94497981,  11.19782891,  15.61723356,  15.29002159,
         6.29218756,  27.1117396 ,  22.14677891,  12.87085541,
        20.08954586,  17.32952015,   3.68586648,  36.19313656,
        14.53188133,  28.12175551,  24.16958979,  21.67895718,
        10.2244178 ,  19.99326995,  78.12026305,  64.31363625,
        27.69862198,  17.51999446,  25.37847633,   8.12665688,
        12.07010387,   9.88400792,  22.068056  ,   7.43773253,
        13.4508131 ,  17.02405462,  51.21372771,  21.38753831,
        24.18420077,  15.63243236,  14.40447562,  27.32547046,
        21.2385719 ,  34.23854031,   3.05114297,  19.69042135,
        44.6947938 ,  19.21966178,  56.50636209,  19.64829371,
        37.74545727,  25.30475501,  21.66545424,   1.03311187,
        68.01812049,  17.63894761,  17.82562234,  69.78440224,
        20.71613028,   2.49098366,  24.35007499,   2.2021248 ,
         6.64017135,  20.28200152,  20.85278965,  20.80555277,
        43.38611629,  27.31398451,  29.53987444,  12.24268115,
         8.6959653 ,  42.03305291,  37.85729566,  33.11579778,
        15.96987065,  21.76147088,  15.03691384,  14.58731786,
        33.41236266,  80.31155666,  29.4725191 ,  11.89050039,
        61.97137191,  15.61848991,  19.2179298 ,  24.10835425,
       126.3009792 ,  27.3962477 ,  59.2122218 ,   5.41380137,
        63.37388558,  35.67669935,  17.68310397,  15.17667146,
        63.99499981,  15.36122647,  30.78592064,  73.56935591,
        20.44229748, 121.96601961,  39.79988826,  84.18869074,
        93.95655296,  71.73577011,  29.33762638,  20.74224949,
        31.58094144,  55.7880665 ,  29.02369948,  39.92892725,
        45.51365479,   8.27935495,   4.45701446,  70.15533868,
        28.41488651,   1.35626754,  39.33215458,  15.07755551,
        21.84105593,   8.90170773,  11.51678639,  21.74549034,
        12.42284438,  -0.23328871,  22.03787894,   0.90094106])

In [15]:
standardScaler = StandardScaler()
standardScaler.fit(X_train)
X_train_standard = standardScaler.transform(X_train)

lin_reg2 = LinearRegression()
lin_reg2.fit_sgd(X_train_standard, y_train, n_iters=20)
lin_reg2.score(X_train_standard, y_train)

0.8547529403802075

In [16]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, seed=666)

In [19]:
lin_reg3 = LinearRegression()
lin_reg3.fit_gd(X_train, y_train, eta=0.00001)
lin_reg3.score(X_test, y_test)

0.8580316106815553